# Generated by Django 5.0.2 on 2024-02-28 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('web', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('link_article', models.URLField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.media')),
            ],
        ),
        migrations.CreateModel(
            name='Rss_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('politica', 'dolítica'), ('deporte', 'deporte'), ('tecnologia', 'tecnologia'), ('economia', 'economia'), ('entretenimiento', 'entretenimiento'), ('espectaculos', 'espectaculos'), ('salud', 'salud'), ('ciencia', 'ciencia'), ('mundo', 'mundo'), ('cultura', 'cultura'), ('opinion', 'opinion')], max_length=50)),
                ('rss', models.URLField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.media')),
            ],
        ),
        migrations.DeleteModel(
            name='Medio',
        ),
    ]
