# Generated by Django 5.0.2 on 2024-04-24 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_media_new_rss_url_delete_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='rss_url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.rss_url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rss_url',
            name='category',
            field=models.CharField(choices=[('politica', 'política'), ('deporte', 'deporte'), ('tecnologia', 'tecnologia'), ('economia', 'economia'), ('entretenimiento', 'entretenimiento'), ('espectaculos', 'espectaculos'), ('salud', 'salud'), ('ciencia', 'ciencia'), ('mundo', 'mundo'), ('cultura', 'cultura'), ('opinion', 'opinion')], max_length=50),
        ),
    ]
