# Generated by Django 5.0.6 on 2024-06-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='characterisrics',
            field=models.JSONField(default=list),
        ),
    ]
