# Generated by Django 5.0.6 on 2024-07-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_validation_characterisrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validation',
            name='cantitems',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='inferences',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='list_items',
        ),
    ]
