# Generated by Django 5.0.6 on 2024-07-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_validation_cantitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='cantitems',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='validation',
            name='inferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='validation',
            name='list_items',
            field=models.JSONField(default=list),
        ),
    ]
