# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag_id: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get timestamp # get the date of the build
        id: date
        run: echo "date=$(TZ=':America/Bogota' date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo $DOCKER_TOKEN | docker login --username cdapdev2020 --password-stdin

      - name: Build images
        run: |
          docker build -t cdapdev2020/truesield-manager-server:${{ steps.date.outputs.date }} .
        
      - name: Push image
        run: |
          docker push cdapdev2020/truesield-manager-server:${{ steps.date.outputs.date }}
          


  